# Generated by Django 5.0.6 on 2024-05-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubnetGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IpAdress', models.CharField(max_length=18)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
