# Generated by Django 5.0.6 on 2024-05-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subnets', '0002_subnetgen_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subnetgen',
            old_name='IpAdress',
            new_name='IpAdresswithCDIR',
        ),
    ]
